[build]
    functions = "functions"
    publish =  "dist"

[dev]
    publish = "dist"
    port = 8080

[functions]
    directory = "functions"
    included_files = ["./users.json"]

[[headers]]
    for = "/*"
        [headers.values]
        Access-Control-Allow-Origin = "*"
        Access-Control-Allow-Methods = "GET,POST,PATCH,DELETE"
        Access-Control-Allow-Headers = "*"

[[redirects]]
    to = "/.netlify/functions/api/:splat"
    from = "/*"
    status = 200