[build]
    functions = "functions"

[dev]
    publish = "dist"

[functions]
    directory = "functions"
    included_files = ["users.json"]

[[redirects]]
    to = "/.netlify/functions/api/:splat"
    from = "/*"
    status = 200